In [1]:
from dotenv import load_dotenv
load_dotenv()

import os

API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")

print(API_KEY)

2UQ6PO6AOFDYC51G

In [2]:
import requests
import pandas as pd
BASE_URL = "https://www.alphavantage.co/query"

In [3]:
def fetch_stock_data(symbol):
    
    params = {
        "function" : "TIME_SERIES_DAILY",
        "symbol": symbol,
        "apikey" : API_KEY 
    }

    response = requests.get(BASE_URL, params=params)
    print(response)
    return response.json()

In [4]:
data = fetch_stock_data("RELIANCE.BSE")
data

<Response [200]>

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'RELIANCE.BSE',
  '3. Last Refreshed': '2026-03-20',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2026-03-20': {'1. open': '1395.7500',
   '2. high': '1430.0000',
   '3. low': '1395.7500',
   '4. close': '1414.5500',
   '5. volume': '1129685'},
  '2026-03-19': {'1. open': '1385.0500',
   '2. high': '1415.8000',
   '3. low': '1376.4000',
   '4. close': '1385.3500',
   '5. volume': '1739524'},
  '2026-03-18': {'1. open': '1402.9000',
   '2. high': '1412.9500',
   '3. low': '1398.7500',
   '4. close': '1408.5000',
   '5. volume': '615653'},
  '2026-03-17': {'1. open': '1400.0000',
   '2. high': '1406.0000',
   '3. low': '1388.6000',
   '4. close': '1396.4500',
   '5. volume': '688080'},
  '2026-03-16': {'1. open': '1381.9000',
   '2. high': '1397.4500',
   '3. low': '1363.4000',
   '4. close': '1395.0500',
   '5. volume': '604567'},
  '2026-03-13': {'1. open': '1388.6500',
   '2. high': '1400.5000',
   '3. low': '1378.3500',
   '4. close': '1380.6000',
   '5. volume': '1358137'},
  '2026-03-12': {'1. open': '1392.7500',
   '2. high': '1410.9000',
   '3. low': '1380.9500',
   '4. close': '1391.8500',
   '5. volume': '1733925'},
  '2026-03-11': {'1. open': '1427.0000',
   '2. high': '1433.6500',
   '3. low': '1383.1000',
   '4. close': '1391.1000',
   '5. volume': '1867413'},
  '2026-03-10': {'1. open': '1427.9500',
   '2. high': '1430.0000',
   '3. low': '1400.6000',
   '4. close': '1409.0500',
   '5. volume': '622230'},
  '2026-03-09': {'1. open': '1372.0500',
   '2. high': '1429.0000',
   '3. low': '1369.0000',
   '4. close': '1424.4500',
   '5. volume': '1316623'},
  '2026-03-06': {'1. open': '1392.2500',
   '2. high': '1424.1000',
   '3. low': '1390.1000',
   '4. close': '1405.2000',
   '5. volume': '1104703'},
  '2026-03-05': {'1. open': '1349.3000',
   '2. high': '1399.0000',
   '3. low': '1349.3000',
   '4. close': '1389.8000',
   '5. volume': '1513497'},
  '2026-03-04': {'1. open': '1325.0000',
   '2. high': '1353.0000',
   '3. low': '1307.0000',
   '4. close': '1345.5500',
   '5. volume': '1759747'},
  '2026-03-02': {'1. open': '1351.4500',
   '2. high': '1378.3000',
   '3. low': '1341.7000',
   '4. close': '1358.3500',
   '5. volume': '1069793'},
  '2026-02-27': {'1. open': '1401.1000',
   '2. high': '1410.5500',
   '3. low': '1388.0000',
   '4. close': '1394.3000',
   '5. volume': '288309'},
  '2026-02-26': {'1. open': '1399.9500',
   '2. high': '1412.6500',
   '3. low': '1391.6000',
   '4. close': '1405.4500',
   '5. volume': '3146620'},
  '2026-02-25': {'1. open': '1436.0000',
   '2. high': '1440.0000',
   '3. low': '1393.5000',
   '4. close': '1398.2000',
   '5. volume': '820874'},
  '2026-02-24': {'1. open': '1426.9500',
   '2. high': '1433.4500',
   '3. low': '1415.0000',
   '4. close': '1430.1500',
   '5. volume': '218568'},
  '2026-02-23': {'1. open': '1420.2500',
   '2. high': '1434.9000',
   '3. low': '1418.3000',
   '4. close': '1427.9000',
   '5. volume': '488729'},
  '2026-02-20': {'1. open': '1410.0000',
   '2. high': '1427.7500',
   '3. low': '1406.8500',
   '4. close': '1420.0500',
   '5. volume': '357252'},
  '2026-02-19': {'1. open': '1441.5500',
   '2. high': '1444.0500',
   '3. low': '1401.0000',
   '4. close': '1410.8000',
   '5. volume': '1156640'},
  '2026-02-18': {'1. open': '1425.4000',
   '2. high': '1442.3500',
   '3. low': '1419.0000',
   '4. close': '1441.2500',
   '5. volume': '368386'},
  '2026-02-17': {'1. open': '1432.4000',
   '2. high': '1432.4000',
   '3. low': '1418.8000',
   '4. close': '1422.8000',
   '5. volume': '180120'},
  '2026-02-16': {'1. open': '1418.2500',
   '2. high': '1439.0000',
   '3. low': '1409.2000',
   '4. close': '1436.4000',
   '5. volume': '477800'},
  '2026-02-13': {'1. open': '1440.4000',
   '2. high': '1451.4500',
   '3. low': '1416.2000',
   '4. close': '1419.9000',
   '5. volume': '793137'},
  '2026-02-12': {'1. open': '1468.6000',
   '2. high': '1473.2000',
   '3. low': '1445.5500',
   '4. close': '1449.8500',
   '5. volume': '1590356'},
  '2026-02-11': {'1. open': '1458.5500',
   '2. high': '1469.9000',
   '3. low': '1454.4500',
   '4. close': '1468.5500',
   '5. volume': '405321'},
  '2026-02-10': {'1. open': '1466.3000',
   '2. high': '1470.5500',
   '3. low': '1452.6000',
   '4. close': '1458.5500',
   '5. volume': '274911'},
  '2026-02-09': {'1. open': '1459.9000',
   '2. high': '1465.7500',
   '3. low': '1453.1500',
   '4. close': '1461.4000',
   '5. volume': '390479'},
  '2026-02-06': {'1. open': '1440.0500',
   '2. high': '1452.8000',
   '3. low': '1433.1000',
   '4. close': '1450.8500',
   '5. volume': '348407'},
  '2026-02-05': {'1. open': '1457.0000',
   '2. high': '1460.9000',
   '3. low': '1439.6500',
   '4. close': '1443.4000',
   '5. volume': '1560195'},
  '2026-02-04': {'1. open': '1438.1000',
   '2. high': '1464.0500',
   '3. low': '1438.1000',
   '4. close': '1456.6000',
   '5. volume': '837314'},
  '2026-02-03': {'1. open': '1481.4500',
   '2. high': '1489.0000',
   '3. low': '1431.0000',
   '4. close': '1437.8500',
   '5. volume': '878787'},
  '2026-02-02': {'1. open': '1341.0000',
   '2. high': '1392.9000',
   '3. low': '1336.0000',
   '4. close': '1390.1500',
   '5. volume': '327928'},
  '2026-01-30': {'1. open': '1384.1000',
   '2. high': '1398.0000',
   '3. low': '1379.2500',
   '4. close': '1395.9000',
   '5. volume': '653980'},
  '2026-01-29': {'1. open': '1399.9500',
   '2. high': '1402.6500',
   '3. low': '1385.9000',
   '4. close': '1391.9000',
   '5. volume': '1593526'},
  '2026-01-28': {'1. open': '1383.3000',
   '2. high': '1409.7000',
   '3. low': '1383.3000',
   '4. close': '1397.0500',
   '5. volume': '785854'},
  '2026-01-27': {'1. open': '1385.8500',
   '2. high': '1391.9000',
   '3. low': '1368.5000',
   '4. close': '1381.0500',
   '5. volume': '3536849'},
  '2026-01-23': {'1. open': '1403.9500',
   '2. high': '1407.1500',
   '3. low': '1381.1500',
   '4. close': '1385.9500',
   '5. volume': '203908'},
  '2026-01-22': {'1. open': '1410.2000',
   '2. high': '1419.7500',
   '3. low': '1395.1000',
   '4. close': '1401.8000',
   '5. volume': '712993'},
  '2026-01-21': {'1. open': '1388.0500',
   '2. high': '1412.7000',
   '3. low': '1373.0000',
   '4. close': '1403.9000',
   '5. volume': '416973'},
  '2026-01-20': {'1. open': '1414.9500',
   '2. high': '1415.7500',
   '3. low': '1390.1000',
   '4. close': '1393.4000',
   '5. volume': '261965'},
  '2026-01-19': {'1. open': '1455.0500',
   '2. high': '1455.0500',
   '3. low': '1403.3000',
   '4. close': '1413.2500',
   '5. volume': '577607'},
  '2026-01-16': {'1. open': '1459.9000',
   '2. high': '1479.6500',
   '3. low': '1455.5000',
   '4. close': '1457.6000',
   '5. volume': '354962'},
  '2026-01-14': {'1. open': '1449.3500',
   '2. high': '1466.8000',
   '3. low': '1439.8500',
   '4. close': '1458.4500',
   '5. volume': '610968'},
  '2026-01-13': {'1. open': '1485.5000',
   '2. high': '1486.0000',
   '3. low': '1445.1500',
   '4. close': '1451.5000',
   '5. volume': '602566'},
  '2026-01-12': {'1. open': '1475.3000',
   '2. high': '1485.0000',
   '3. low': '1451.1000',
   '4. close': '1483.3000',
   '5. volume': '568998'},
  '2026-01-09': {'1. open': '1466.9500',
   '2. high': '1480.0000',
   '3. low': '1465.0000',
   '4. close': '1475.3000',
   '5. volume': '234309'},
  '2026-01-08': {'1. open': '1503.7500',
   '2. high': '1503.7500',
   '3. low': '1468.4500',
   '4. close': '1470.3000',
   '5. volume': '2168603'},
  '2026-01-07': {'1. open': '1510.0000',
   '2. high': '1519.9500',
   '3. low': '1498.2000',
   '4. close': '1504.1000',
   '5. volume': '710599'},
  '2026-01-06': {'1. open': '1575.5500',
   '2. high': '1575.5500',
   '3. low': '1497.0500',
   '4. close': '1507.7000',
   '5. volume': '956028'},
  '2026-01-05': {'1. open': '1592.5000',
   '2. high': '1611.2000',
   '3. low': '1575.0000',
   '4. close': '1577.4500',
   '5. volume': '489517'},
  '2026-01-02': {'1. open': '1579.9500',
   '2. high': '1594.4500',
   '3. low': '1578.0000',
   '4. close': '1592.4500',
   '5. volume': '381201'},
  '2026-01-01': {'1. open': '1571.3500',
   '2. high': '1592.9000',
   '3. low': '1571.0000',
   '4. close': '1574.9000',
   '5. volume': '871193'},
  '2025-12-31': {'1. open': '1540.0500',
   '2. high': '1576.5000',
   '3. low': '1540.0500',
   '4. close': '1569.4000',
   '5. volume': '437555'},
  '2025-12-30': {'1. open': '1543.3500',
   '2. high': '1553.6000',
   '3. low': '1538.0000',
   '4. close': '1540.8000',
   '5. volume': '232715'},
  '2025-12-29': {'1. open': '1558.9500',
   '2. high': '1558.9500',
   '3. low': '1543.1500',
   '4. close': '1545.3000',
   '5. volume': '167579'},
  '2025-12-26': {'1. open': '1555.0000',
   '2. high': '1561.0000',
   '3. low': '1554.8000',
   '4. close': '1559.0000',
   '5. volume': '113233'},
  '2025-12-24': {'1. open': '1571.0500',
   '2. high': '1575.0000',
   '3. low': '1553.8500',
   '4. close': '1557.9500',
   '5. volume': '712435'},
  '2025-12-23': {'1. open': '1576.0500',
   '2. high': '1580.0000',
   '3. low': '1568.0500',
   '4. close': '1570.9000',
   '5. volume': '464178'},
  '2025-12-22': {'1. open': '1568.2000',
   '2. high': '1577.0000',
   '3. low': '1565.6000',
   '4. close': '1575.4500',
   '5. volume': '382704'},
  '2025-12-19': {'1. open': '1552.8000',
   '2. high': '1573.9000',
   '3. low': '1551.0500',
   '4. close': '1565.1000',
   '5. volume': '256444'},
  '2025-12-18': {'1. open': '1539.9500',
   '2. high': '1551.0000',
   '3. low': '1536.0000',
   '4. close': '1544.3500',
   '5. volume': '1018167'},
  '2025-12-17': {'1. open': '1550.0000',
   '2. high': '1550.0000',
   '3. low': '1539.3000',
   '4. close': '1544.6000',
   '5. volume': '240805'},
  '2025-12-16': {'1. open': '1548.0000',
   '2. high': '1551.5500',
   '3. low': '1539.4000',
   '4. close': '1541.8000',
   '5. volume': '126933'},
  '2025-12-15': {'1. open': '1555.9500',
   '2. high': '1557.9500',
   '3. low': '1547.0000',
   '4. close': '1556.0500',
   '5. volume': '162363'},
  '2025-12-12': {'1. open': '1549.0500',
   '2. high': '1559.5000',
   '3. low': '1546.6000',
   '4. close': '1556.0000',
   '5. volume': '102402'},
  '2025-12-11': {'1. open': '1536.3000',
   '2. high': '1549.9500',
   '3. low': '1523.7500',
   '4. close': '1544.9000',
   '5. volume': '1127154'},
  '2025-12-10': {'1. open': '1532.0000',
   '2. high': '1547.5000',
   '3. low': '1530.9000',
   '4. close': '1535.3000',
   '5. volume': '1143477'},
  '2025-12-09': {'1. open': '1540.0000',
   '2. high': '1542.9500',
   '3. low': '1520.3500',
   '4. close': '1528.8000',
   '5. volume': '817126'},
  '2025-12-08': {'1. open': '1533.0500',
   '2. high': '1550.8000',
   '3. low': '1533.0500',
   '4. close': '1542.5500',
   '5. volume': '1730253'},
  '2025-12-05': {'1. open': '1531.8000',
   '2. high': '1546.0000',
   '3. low': '1520.4500',
   '4. close': '1540.9000',
   '5. volume': '308198'},
  '2025-12-04': {'1. open': '1536.0500',
   '2. high': '1560.1000',
   '3. low': '1518.0000',
   '4. close': '1538.4000',
   '5. volume': '1432313'},
  '2025-12-03': {'1. open': '1546.4000',
   '2. high': '1552.0000',
   '3. low': '1533.1000',
   '4. close': '1539.0000',
   '5. volume': '420895'},
  '2025-12-02': {'1. open': '1560.0500',
   '2. high': '1567.0000',
   '3. low': '1542.2500',
   '4. close': '1546.4000',
   '5. volume': '110289'},
  '2025-12-01': {'1. open': '1575.0000',
   '2. high': '1579.9500',
   '3. low': '1563.7500',
   '4. close': '1565.9000',
   '5. volume': '162025'},
  '2025-11-28': {'1. open': '1568.0000',
   '2. high': '1580.9000',
   '3. low': '1562.3500',
   '4. close': '1566.8500',
   '5. volume': '479141'},
  '2025-11-27': {'1. open': '1575.2500',
   '2. high': '1575.2500',
   '3. low': '1556.0000',
   '4. close': '1563.5500',
   '5. volume': '1112784'},
  '2025-11-26': {'1. open': '1545.0000',
   '2. high': '1571.8000',
   '3. low': '1541.0000',
   '4. close': '1569.7500',
   '5. volume': '485790'},
  '2025-11-25': {'1. open': '1535.0000',
   '2. high': '1560.0000',
   '3. low': '1525.0000',
   '4. close': '1539.1000',
   '5. volume': '229673'},
  '2025-11-24': {'1. open': '1548.1000',
   '2. high': '1550.0000',
   '3. low': '1532.9000',
   '4. close': '1535.7500',
   '5. volume': '236624'},
  '2025-11-21': {'1. open': '1541.0000',
   '2. high': '1557.9500',
   '3. low': '1539.0000',
   '4. close': '1545.9500',
   '5. volume': '514303'},
  '2025-11-20': {'1. open': '1530.0000',
   '2. high': '1550.9000',
   '3. low': '1526.8000',
   '4. close': '1549.1000',
   '5. volume': '1873543'},
  '2025-11-19': {'1. open': '1514.0000',
   '2. high': '1522.2000',
   '3. low': '1511.7000',
   '4. close': '1518.6500',
   '5. volume': '289954'},
  '2025-11-18': {'1. open': '1523.6500',
   '2. high': '1527.8000',
   '3. low': '1510.0500',
   '4. close': '1519.6500',
   '5. volume': '155896'},
  '2025-11-17': {'1. open': '1518.8500',
   '2. high': '1523.5000',
   '3. low': '1511.4500',
   '4. close': '1517.9000',
   '5. volume': '214052'},
  '2025-11-14': {'1. open': '1506.8000',
   '2. high': '1520.7000',
   '3. low': '1506.0000',
   '4. close': '1518.8500',
   '5. volume': '283160'},
  '2025-11-13': {'1. open': '1512.5000',
   '2. high': '1522.0000',
   '3. low': '1505.6000',
   '4. close': '1510.6000',
   '5. volume': '1136211'},
  '2025-11-12': {'1. open': '1500.0000',
   '2. high': '1524.0000',
   '3. low': '1500.0000',
   '4. close': '1511.7500',
   '5. volume': '854483'},
  '2025-11-11': {'1. open': '1496.0000',
   '2. high': '1498.7000',
   '3. low': '1480.2500',
   '4. close': '1493.9000',
   '5. volume': '214867'},
  '2025-11-10': {'1. open': '1473.1500',
   '2. high': '1500.0000',
   '3. low': '1473.1500',
   '4. close': '1489.2500',
   '5. volume': '408088'},
  '2025-11-07': {'1. open': '1497.6500',
   '2. high': '1498.5000',
   '3. low': '1476.2500',
   '4. close': '1478.2500',
   '5. volume': '378528'},
  '2025-11-06': {'1. open': '1483.1000',
   '2. high': '1501.9500',
   '3. low': '1477.5500',
   '4. close': '1495.7500',
   '5. volume': '1178418'},
  '2025-11-04': {'1. open': '1484.3000',
   '2. high': '1492.7000',
   '3. low': '1470.3000',
   '4. close': '1471.8500',
   '5. volume': '265941'},
  '2025-11-03': {'1. open': '1486.0000',
   '2. high': '1495.0000',
   '3. low': '1479.1500',
   '4. close': '1484.3500',
   '5. volume': '548207'},
  '2025-10-31': {'1. open': '1491.0000',
   '2. high': '1497.8000',
   '3. low': '1482.0000',
   '4. close': '1486.5000',
   '5. volume': '268477'},
  '2025-10-30': {'1. open': '1500.0000',
   '2. high': '1503.2500',
   '3. low': '1484.0000',
   '4. close': '1488.4500',
   '5. volume': '772640'},
  '2025-10-29': {'1. open': '1489.0000',
   '2. high': '1508.0000',
   '3. low': '1488.7000',
   '4. close': '1504.0500',
   '5. volume': '750041'},
  '2025-10-28': {'1. open': '1480.1500',
   '2. high': '1492.1000',
   '3. low': '1478.0000',
   '4. close': '1487.1500',
   '5. volume': '1341632'},
  '2025-10-27': {'1. open': '1461.2500',
   '2. high': '1484.9500',
   '3. low': '1458.7000',
   '4. close': '1484.0000',
   '5. volume': '393023'}}}

In [5]:
data.keys()

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [6]:
time_series = data["Time Series (Daily)"]
len(time_series)

100

In [7]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from backend.api.market_data import fetch_stock_data



def pase_stock_data(data) :
    """
    Extract time serise data from API response
    """

    if "Time Series (Daily)" not in data:
        raise Exception("Time Serises data not found in API response")

    return data["Time Series (Daily)"]


data = fetch_stock_data("RELIANCE.BSE")

In [8]:
time_series = pase_stock_data(data)
print(list(time_series.keys())[:5])

['2026-03-20', '2026-03-19', '2026-03-18', '2026-03-17', '2026-03-16']

In [9]:
import pandas as pd

df = pd.DataFrame(time_series).T
df = df.rename(columns={
    "1. open" :"Open",
    "2. high" :"High" ,  
    "3. low"  :"Low" , 
    "4. close" :"Close"  ,
    "5. volume" : "Volume"
})

df = df.astype(float)
df["Volume"] = df["Volume"].astype(int)

df.index = pd.to_datetime(df.index)

df = df.sort_index(ascending=False)
df.reset_index(inplace=True)
df.rename(columns={"index":"Date"},inplace=True)
df = df.set_index("Date")
print(df[:5])

               Open     High      Low    Close   Volume
Date
2026-03-20  1395.75  1430.00  1395.75  1414.55  1129685
2026-03-19  1385.05  1415.80  1376.40  1385.35  1739524
2026-03-18  1402.90  1412.95  1398.75  1408.50   615653
2026-03-17  1400.00  1406.00  1388.60  1396.45   688080
2026-03-16  1381.90  1397.45  1363.40  1395.05   604567

In [10]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 100 entries, 2026-03-20 to 2025-10-27
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    100 non-null    float64
 1   High    100 non-null    float64
 2   Low     100 non-null    float64
 3   Close   100 non-null    float64
 4   Volume  100 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 4.7 KB

In [11]:
describe_data = df.describe()
describe_data = describe_data.astype(float)
describe_data["Volume"] =  describe_data["Volume"].astype(int)
describe_data

              Open         High          Low        Close   Volume
count   100.000000   100.000000   100.000000   100.000000      100
mean   1477.095000  1490.183000  1464.723000  1476.773000   747810
std      67.716266    64.347758    69.034887    65.786968   620730
min    1325.000000  1353.000000  1307.000000  1345.550000   102402
25%    1419.750000  1431.800000  1400.137500  1412.637500   289542
50%    1482.275000  1492.400000  1469.375000  1480.775000   558602
75%    1539.962500  1550.925000  1531.400000  1540.825000  1078520
max    1592.500000  1611.200000  1578.000000  1592.450000  3536849

In [12]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [13]:
df.dtypes

Open      float64
High      float64
Low       float64
Close     float64
Volume      int64
dtype: object

In [14]:
df.head()

               Open     High      Low    Close   Volume
Date
2026-03-20  1395.75  1430.00  1395.75  1414.55  1129685
2026-03-19  1385.05  1415.80  1376.40  1385.35  1739524
2026-03-18  1402.90  1412.95  1398.75  1408.50   615653
2026-03-17  1400.00  1406.00  1388.60  1396.45   688080
2026-03-16  1381.90  1397.45  1363.40  1395.05   604567

In [15]:
if df.isnull().sum().sum() > 0:
    print("Missing Values found")
else :
    print("Missing Values not found")

Missing Values not found

In [16]:
if (df["High"] < df["Low"]).any() :
    print("Invalid price data")
else :
    print("Price Data Valid")

Price Data Valid

In [17]:
def validated_data(df) :
    """
    Validated stock data
    """

    print("\n --- Data Info ---")
    print(df.info())

    print("\n --- Summary Statistics ---")
    describe_data = df.describe()
    describe_data = describe_data.astype(float).round(2)
    describe_data["Volume"] =  describe_data["Volume"].astype(int)
    print(describe_data)

    print("\n --- Missing Value found ---")
    print(df.isnull().sum())

    #Logical Checks

    if df.isnull().sum().sum() > 0 :
        raise Exception("Missing values found")
    
    print("\n Data validation successful ✅")

In [18]:
validated_data(df)

 --- Data Info ---
<class 'pandas.DataFrame'>
DatetimeIndex: 100 entries, 2026-03-20 to 2025-10-27
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    100 non-null    float64
 1   High    100 non-null    float64
 2   Low     100 non-null    float64
 3   Close   100 non-null    float64
 4   Volume  100 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 4.7 KB
None

 --- Summary Statistics ---
          Open     High      Low    Close   Volume
count   100.00   100.00   100.00   100.00      100
mean   1477.09  1490.18  1464.72  1476.77   747810
std      67.72    64.35    69.03    65.79   620730
min    1325.00  1353.00  1307.00  1345.55   102402
25%    1419.75  1431.80  1400.14  1412.64   289542
50%    1482.28  1492.40  1469.38  1480.78   558602
75%    1539.96  1550.93  1531.40  1540.82  1078520
max    1592.50  1611.20  1578.00  1592.45  3536849

 --- Missing Value found ---
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

 Data validation successful ✅

In [19]:
df = df.copy()

In [20]:
df.columns.str.lower()

Index(['open', 'high', 'low', 'close', 'volume'], dtype='str')

In [21]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [22]:
df.dropna()

               Open     High      Low    Close   Volume
Date
2026-03-20  1395.75  1430.00  1395.75  1414.55  1129685
2026-03-19  1385.05  1415.80  1376.40  1385.35  1739524
2026-03-18  1402.90  1412.95  1398.75  1408.50   615653
2026-03-17  1400.00  1406.00  1388.60  1396.45   688080
2026-03-16  1381.90  1397.45  1363.40  1395.05   604567
...             ...      ...      ...      ...      ...
2025-10-31  1491.00  1497.80  1482.00  1486.50   268477
2025-10-30  1500.00  1503.25  1484.00  1488.45   772640
2025-10-29  1489.00  1508.00  1488.70  1504.05   750041
2025-10-28  1480.15  1492.10  1478.00  1487.15  1341632
2025-10-27  1461.25  1484.95  1458.70  1484.00   393023

[100 rows x 5 columns]

In [23]:
df["Close_norm"] = (df["Close"] /  df["Close"].max()).astype(float).round(2)

print(df)

               Open     High      Low    Close   Volume  Close_norm
Date
2026-03-20  1395.75  1430.00  1395.75  1414.55  1129685        0.89
2026-03-19  1385.05  1415.80  1376.40  1385.35  1739524        0.87
2026-03-18  1402.90  1412.95  1398.75  1408.50   615653        0.88
2026-03-17  1400.00  1406.00  1388.60  1396.45   688080        0.88
2026-03-16  1381.90  1397.45  1363.40  1395.05   604567        0.88
...             ...      ...      ...      ...      ...         ...
2025-10-31  1491.00  1497.80  1482.00  1486.50   268477        0.93
2025-10-30  1500.00  1503.25  1484.00  1488.45   772640        0.93
2025-10-29  1489.00  1508.00  1488.70  1504.05   750041        0.94
2025-10-28  1480.15  1492.10  1478.00  1487.15  1341632        0.93
2025-10-27  1461.25  1484.95  1458.70  1484.00   393023        0.93

[100 rows x 6 columns]

In [24]:
df["retuens"] = (df["Close"].pct_change()).astype(float).round(5)

In [25]:
df["pct_change"] = (df["Close"].pct_change() * 100).astype(float).round(2)
df

,Open,High,Low,Close,Volume,Close_norm,retuens,pct_change
Date,,,,,,,,
2026-03-20,1395.75,1430.00,1395.75,1414.55,1129685,0.89,NaN,NaN
2026-03-19,1385.05,1415.80,1376.40,1385.35,1739524,0.87,-0.02064,-2.06
2026-03-18,1402.90,1412.95,1398.75,1408.50,615653,0.88,0.01671,1.67
2026-03-17,1400.00,1406.00,1388.60,1396.45,688080,0.88,-0.00856,-0.86
2026-03-16,1381.90,1397.45,1363.40,1395.05,604567,0.88,-0.00100,-0.10
...,...,...,...,...,...,...,...,...
2025-10-31,1491.00,1497.80,1482.00,1486.50,268477,0.93,0.00145,0.14
2025-10-30,1500.00,1503.25,1484.00,1488.45,772640,0.93,0.00131,0.13
2025-10-29,1489.00,1508.00,1488.70,1504.05,750041,0.94,0.01048,1.05
2025-10-28,1480.15,1492.10,1478.00,1487.15,1341632,0.93,-0.01124,-1.12
2025-10-27,1461.25,1484.95,1458.70,1484.00,393023,0.93,-0.00212,-0.21

In [26]:
stats = {}

# core return stats
stats["mean"] = round(float(df["retuens"].mean()),6)
stats["median"] = round(float(df["retuens"].median()),6)
stats["std_dev"] = round(float(df["retuens"].std()),6)
stats["variance"] =  round(float(df["retuens"].var()),6)

# Extremes

stats["min"] =  round(float(df["retuens"].min()),6)
stats["max"] =  round(float(df["retuens"].max()),6)

#Percentiles

stats["percentiles"] = {
    "25" :round(float(df["retuens"].quantile(0.25)),6),
    "50" :round(float(df["retuens"].quantile(0.50)),6),
    "75" :round(float(df["retuens"].quantile(0.75)),6),
    "5"  :round(float(df["retuens"].quantile(0.05)),6),
    "95" :round(float(df["retuens"].quantile(0.95)),6),

}

print(stats)

{'mean': 0.00056, 'median': -3e-05, 'std_dev': 0.012337, 'variance': 0.000152, 'min': -0.03317, 'max': 0.04626, 'percentiles': {'25': -0.00654, '50': -3e-05, '75': 0.0084, '5': -0.018351, '95': 0.022004}}

In [56]:
def compute_relationships(df):

    corr = df[["Open","High","Low","Close"]].corr()
    cov = df[["Open","High","Low","Close"]].cov()
    
    #round
    corr = corr.round(4)
    cov = cov.round(2)
    

    return {
        "correlation": corr.to_dict(),
        "covariance": cov.to_dict(),
        "correlation_matrix" : corr.values.tolist(),
        "lables" : corr.columns.tolist()

        
    }

In [57]:
compute_relationships(df)

{'correlation': {'Open': {'Open': 1.0,
   'High': 0.9865,
   'Low': 0.9818,
   'Close': 0.9628},
  'High': {'Open': 0.9865, 'High': 1.0, 'Low': 0.9846, 'Close': 0.9837},
  'Low': {'Open': 0.9818, 'High': 0.9846, 'Low': 1.0, 'Close': 0.9891},
  'Close': {'Open': 0.9628, 'High': 0.9837, 'Low': 0.9891, 'Close': 1.0}},
 'covariance': {'Open': {'Open': 4585.49,
   'High': 4298.41,
   'Low': 4589.93,
   'Close': 4289.3},
  'High': {'Open': 4298.41, 'High': 4140.63, 'Low': 4373.62, 'Close': 4164.44},
  'Low': {'Open': 4589.93, 'High': 4373.62, 'Low': 4765.82, 'Close': 4492.29},
  'Close': {'Open': 4289.3,
   'High': 4164.44,
   'Low': 4492.29,
   'Close': 4327.93}},
 'correlation_matrix': [[1.0, 0.9865, 0.9818, 0.9628],
  [0.9865, 1.0, 0.9846, 0.9837],
  [0.9818, 0.9846, 1.0, 0.9891],
  [0.9628, 0.9837, 0.9891, 1.0]],
 'lables': ['Open', 'High', 'Low', 'Close']}

In [ ]:
{
        "correlation": corr.to_dict(),
        "covariance": cov.to_dict(),
        "correlation_matrix" : corr.values.tolist(),
        "lables" : corr.columns.tolist()

        
    }